# Generated by Django 3.0.9 on 2020-12-14 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='entry_fields',
            new_name='entry',
        ),
    ]
