# Generated by Django 3.0.9 on 2020-12-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
                ('catagory', models.CharField(choices=[('A', 'Home'), ('B', 'School'), ('C', 'Work')], default='Home', max_length=9)),
                ('completed', models.BooleanField(default='No')),
            ],
        ),
    ]
