# Generated by Django 3.0.9 on 2020-12-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
                ('catagory', models.CharField(choices=[('A', 'Home'), ('B', 'School'), ('C', 'Work'), ('D', 'Self-Improvment'), ('E', 'Other')], default='Home', max_length=8)),
                ('completed', models.CharField(choices=[(True, 'Yes'), (False, 'No')], max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='tasks',
        ),
    ]
