# Generated by Django 3.0.9 on 2020-12-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201201_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='catagory',
            field=models.CharField(choices=[('A', 'Home'), ('B', 'School'), ('C', 'Work'), ('D', 'Self-Improvment'), ('E', 'Other')], max_length=8),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[(True, 'Yes'), (False, 'No')], default='No', max_length=8),
        ),
    ]
