# Generated by Django 3.0.9 on 2020-12-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20201211_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tasks_view_hide_completed',
            field=models.BooleanField(default=False),
        ),
    ]
